// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OVHPoc.Shared;

#nullable disable

namespace OVHPoc.Shared.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240210203501_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("OVHPoc.Shared.Models.MailMigrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MailMigrationRequests");
                });

            modelBuilder.Entity("OVHPoc.Shared.Models.MerelyMail.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MailboxId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("OVHPoc.Shared.Models.MerelyMail.Mail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<int>("MailboxId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("OVHPoc.Shared.Models.MerelyMail.Mailbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mailbox");
                });

            modelBuilder.Entity("OVHPoc.Shared.Models.MerelyMail.Folder", b =>
                {
                    b.HasOne("OVHPoc.Shared.Models.MerelyMail.Mailbox", null)
                        .WithMany("Folders")
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OVHPoc.Shared.Models.MerelyMail.Mail", b =>
                {
                    b.HasOne("OVHPoc.Shared.Models.MerelyMail.Mailbox", null)
                        .WithMany("Mails")
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OVHPoc.Shared.Models.MerelyMail.Mailbox", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Mails");
                });
#pragma warning restore 612, 618
        }
    }
}
